@host = http://localhost
@port = 3001
@base_path = /api/v1

###
@name = getBooks
{{host}}:{{port}}{{base_path}}/search

###
@name = getBooksWithQuery
POST {{host}}:{{port}}{{base_path}}/login
Content-Type: application/json

{
  "user": {
    "email": "dio_the_world9740zero@yahoo.co.jp",
    "password": "9740zero"
  }
}

