@host = http://localhost
@port = 80
@base_path = /api/v1

###
@name = getBooks
GET {{host}}:{{port}}{{base_path}}/review_categories

###
@name = getBooksWithQuery
POST {{host}}:{{port}}{{base_path}}/review_categories
Content-Type: application/json

{
  "reviewCategories": [
    {
    "id": 6,
    "name": "きゅわの有無",
    "created_at": "2021-07-04T08:37:41.000Z",
    "updated_at": "2021-07-04T08:37:41.000Z"
    }
  ]
}

###
@name = logout
DELETE {{host}}:{{port}}{{base_path}}/logout