@host = http://localhost
@port = 3001
@base_path = /api/v1

###
@name = getBooks
{{host}}:{{port}}{{base_path}}/users/1

###
@name = getBooksWithQuery
POST {{host}}:{{port}}{{base_path}}/users
Content-Type: application/json

{
  "user": {
    "name": "guest9",
    "email": "test9@test.com",
    "password": "9740zero",
    "password_confirmation": "9740zero",
    "birthday": "1995-11-16",
    "salary": 300
  }
}

###
@name = logout
DELETE {{host}}:{{port}}{{base_path}}/logout